//! Common
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_IS_SIDEBAR_OPEN = 'SET_IS_SIDEBAR_OPEN';

//! Auth
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const GET_ADMIN_DETAIL = 'GET_ADMIN_DETAIL';
export const SET_ADMIN_DETAIL = 'SET_ADMIN_DETAIL';
export const SET_ADMIN_PERMISSION = 'SET_ADMIN_PERMISSION';

//! Dashboard
export const GET_DASHBOARD = 'GET_DASHBOARD'
export const SET_DASHBOARD = 'SET_DASHBOARD';

//! Users
export const GET_USERS = 'GET_USERS';
export const SET_USERS = 'SET_USERS';
export const UPDATE_USER_STATUS = 'UPDATE_USER_STATUS';

//! contest
export const GET_CONTEST = 'GET_CONTEST';
export const SET_CONTEST = 'SET_CONTEST';
export const CREATE_CONTEST = 'CREATE_CONTEST';
export const UPDATE_CONTEST = 'UPDATE_CONTEST';
export const DELETE_CONTEST = 'DELETE_CONTEST';

//! points
export const GET_POINTS = 'GET_POINTS';
export const SET_POINTS = 'SET_POINTS';

//! Player
export const GET_PLAYER = 'GET_PLAYER';
export const SET_PLAYER = 'SET_PLAYER';
export const CREATE_PLAYER = 'CREATE_PLAYER';
export const UPDATE_PLAYER = 'UPDATE_PLAYER';
export const DELETE_PLAYER = 'DELETE_PLAYER';
export const UPDATE_PLAYER_WALLET = 'UPDATE_PLAYER_WALLET';
export const CHANGE_PLAYER_STATUS = 'CHANGE_PLAYER_STATUS';

//! Game History
export const GET_FTT_GAME_HISTORY = 'GET_FTT_GAME_HISTORY';
export const SET_FTT_GAME_HISTORY = 'SET_FTT_GAME_HISTORY';
export const GET_FST_GAME_HISTORY = 'GET_FST_GAME_HISTORY';
export const SET_FST_GAME_HISTORY = 'SET_FST_GAME_HISTORY';
export const GET_PT_GAME_HISTORY = 'GET_PT_GAME_HISTORY';
export const SET_PT_GAME_HISTORY = 'SET_PT_GAME_HISTORY';

//! Current Game
//* Fun Target Timer
export const GET_CURRENT_FTT_GAME_ID = 'GET_CURRENT_FTT_GAME_ID';
export const SET_CURRENT_FTT_GAME_ID = 'SET_CURRENT_FTT_GAME_ID';
export const GET_CURRENT_FTT_GAME_TOTAL_BETS = 'GET_CURRENT_FTT_GAME_TOTAL_BETS';
export const SET_CURRENT_FTT_GAME_TOTAL_BETS = 'SET_CURRENT_FTT_GAME_TOTAL_BETS';
export const GET_CURRENT_FTT_GAME_TIMER = 'GET_CURRENT_FTT_GAME_TIMER';
export const SET_CURRENT_FTT_GAME_TIMER = 'SET_CURRENT_FTT_GAME_TIMER';
export const CURRENT_FTT_GAME_WINNER_BY_ADMIN = 'CURRENT_FTT_GAME_WINNER_BY_ADMIN';

//* Fun Sorat Timer
export const GET_CURRENT_FST_GAME_ID = 'GET_CURRENT_FST_GAME_ID';
export const SET_CURRENT_FST_GAME_ID = 'SET_CURRENT_FST_GAME_ID';
export const GET_CURRENT_FST_GAME_TOTAL_BETS = 'GET_CURRENT_FST_GAME_TOTAL_BETS';
export const SET_CURRENT_FST_GAME_TOTAL_BETS = 'SET_CURRENT_FST_GAME_TOTAL_BETS';
export const GET_CURRENT_FST_GAME_TIMER = 'GET_CURRENT_FST_GAME_TIMER';
export const SET_CURRENT_FST_GAME_TIMER = 'SET_CURRENT_FST_GAME_TIMER';
export const CURRENT_FST_GAME_WINNER_BY_ADMIN = 'CURRENT_FST_GAME_WINNER_BY_ADMIN';

//* Prologic Timer
export const GET_CURRENT_PT_GAME_ID = 'GET_CURRENT_PT_GAME_ID';
export const SET_CURRENT_PT_GAME_ID = 'SET_CURRENT_PT_GAME_ID';
export const GET_CURRENT_PT_GAME_TOTAL_BETS = 'GET_CURRENT_PT_GAME_TOTAL_BETS';
export const SET_CURRENT_PT_GAME_TOTAL_BETS = 'SET_CURRENT_PT_GAME_TOTAL_BETS';
export const GET_CURRENT_PT_GAME_TIMER = 'GET_CURRENT_PT_GAME_TIMER';
export const SET_CURRENT_PT_GAME_TIMER = 'SET_CURRENT_PT_GAME_TIMER';
export const CURRENT_PT_GAME_WINNER_BY_ADMIN = 'CURRENT_PT_GAME_WINNER_BY_ADMIN';

//! Payment
export const GET_PAYMENT_REQUEST = 'GET_PAYMENT_REQUEST';
export const SET_PAYMENT_REQUEST = 'SET_PAYMENT_REQUEST';
export const GET_PAYMENT_HISTORY = 'GET_PAYMENT_HISTORY';
export const SET_PAYMENT_HISTORY = 'SET_PAYMENT_HISTORY';
export const APPROVE_REJECT_PAYMENT_REQUEST = 'APPROVE_REJECT_PAYMENT_REQUEST';

//! Setting
//* Sub amdin
export const GET_SUB_ADMIN = 'GET_SUB_ADMIN';
export const SET_SUB_ADMIN = 'SET_SUB_ADMIN';
export const CREATE_SUB_ADMIN = 'CREATE_SUB_ADMIN';
export const UPDATE_SUB_ADMIN = 'UPDATE_SUB_ADMIN';
export const DELETE_SUB_ADMIN = 'DELETE_SUB_ADMIN';

//* Admin
export const CHANGE_ADMIN_PASSWORD = 'CHANGE_ADMIN_PASSWORD';

//* Settings
export const SET_PROFIT = 'SET_PROFIT';